set_property(GLOBAL PROPERTY USE_FOLDERS ON)
option(EON_INLINE_TESTS "Include inline unit tests in build?" ON)
option(EON_BUILD_FILESYS "Include the File System package" ON)
option(EON_BUILD_TYPESYSTEM "Include the Type System package" ON)
#option(EON_BUILD_EDT "Build the Eon Data Tuple package")
option(EON_BUILD_EDOC "Build the Eon Documentation package" OFF)
option(EON_BUILD_TOKENIZER "Build the Tokenizer package" ON)
option(EON_BUILD_PARSER "Build the Eon Parser package" OFF)
option(EON_BUILD_EONEDOCGEN "Build the Eon Document Generator" OFF)
option(EON_STATIC_RUNTIME "Use static runtime libraries" ON)

if(EON_STATIC_RUNTIME)
	message(STATUS "Using static runtime.")
	if(CMAKE_C_COMPILER_ID STREQUAL GNU)
		add_link_options(-static-libgcc)
	endif()
	if(CMAKE_CXX_COMPILER_ID STREQUAL GNU)
		add_link_options(-static-libgcc -static-libstdc++)
	endif()
	set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()
