# Add libraries based upon options
if(EON_INLINE_TESTS)
	set(Eon_LIBRARIES
		"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}EonInlineTest${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()
if(EON_BUILD_FILESYS)
	set(Eon_LIBRARIES
		"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}EonFileSys${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()
if(EON_BUILD_TYPESYSTEM)
	set(Eon_LIBRARIES
		"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}EonTypeSystem${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()
if(EON_BUILD_TOKENIZER OR EON_BUILD_TYPESYSTEM OR EON_BUILD_PARSER)
	set(Eon_LIBRARIES
		"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}EonTokenizer${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()
if(EON_BUILD_PARSER)
	set(Eon_LIBRARIES
		"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}EonParser${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()
if(EON_BUILD_PARSER OR EON_BUILD_TYPESYSTEM)
	set(Eon_LIBRARIES
		"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}EonExpression${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()

# Add default libraries
set(Eon_LIBRARIES
	"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}EonTest${CMAKE_STATIC_LIBRARY_SUFFIX}"
	"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}EonTerminal${CMAKE_STATIC_LIBRARY_SUFFIX}"
	"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}EonContainers${CMAKE_STATIC_LIBRARY_SUFFIX}"
	"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}EonString${CMAKE_STATIC_LIBRARY_SUFFIX}"
	"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}EonExcept${CMAKE_STATIC_LIBRARY_SUFFIX}"
	"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}EonRegex${CMAKE_STATIC_LIBRARY_SUFFIX}"
	"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}EonSource${CMAKE_STATIC_LIBRARY_SUFFIX}"
)

# Set include directories
set(Eon_INCLUDE_DIRS "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_INCLUDEDIR}")

# Export the variables
set(Eon_INCLUDE_DIRS ${Eon_INCLUDE_DIRS} CACHE PATH "Eon include directories")
set(Eon_LIBRARIES ${Eon_LIBRARIES} CACHE FILEPATH "Eon libraries")

# Create an imported target for the library
add_library(Eon::eon INTERFACE IMPORTED)
set_target_properties(Eon::eon PROPERTIES
	INTERFACE_INCLUDE_DIRECTORIES "${Eon_INCLUDE_DIRS}"
	INTERFACE_LINK_LIBRARIES "${Eon_LIBRARIES}"
)
