add_subdirectory(eontest)
if(EON_INLINE_TESTS)
	add_subdirectory(eoninlinetest)
endif()

add_subdirectory(eonterminal)
add_subdirectory(eoncontainers)
add_subdirectory(eonstring)
add_subdirectory(eonexcept)
add_subdirectory(eonregex)
add_subdirectory(eonsource)
if(EON_BUILD_TYPESYSTEM OR EON_BUILD_PARSER)
	add_subdirectory(eontypesystem)
	add_subdirectory(eonexpression)
endif()
if(EON_BUILD_FILESYS)
	add_subdirectory(eonfilesys)
endif()
if(EON_BUILD_TOKENIZER OR EON_BUILD_TYPESYSTEM OR EON_BUILD_PARSER)
	add_subdirectory(eontokenizer)
endif()
if(EON_BUILD_EDOC OR EON_BUILD_EONEDOCGEN)
	add_subdirectory(eonedoc)
endif()
if(EON_BUILD_EONEDOCGEN)
	add_subdirectory(eonedocgen)
endif()
if(EON_BUILD_PARSER)
	add_subdirectory(eonparser)
endif()
